name: 'SmallAmp'
description: 'Test amplification for Pharo'
inputs:
  action:  
    description: 'action (setup, amplify, push)'
    required: true
    default: 'setup'
runs:
  using: 'node12'
  main: 'dist/index.js'
  # post: 'dist2/index.js'

